"""Add Schema

Revision ID: fa9b900d542f
Revises: 6098a9127d81
Create Date: 2024-02-17 23:28:35.740514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa9b900d542f'
down_revision: Union[str, None] = '6098a9127d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('status', sa.Enum('ON_SALE', 'SOLD_OUT', name='itemstatus'), nullable=True))
    op.add_column('items', sa.Column('uuid', sa.String(), nullable=True))
    op.drop_column('items', 'satatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('satatus', postgresql.ENUM('ON_SALE', 'SOLD_OUT', name='itemstatus'), autoincrement=False, nullable=False))
    op.drop_column('items', 'uuid')
    op.drop_column('items', 'status')
    # ### end Alembic commands ###
